/**
 * Phone mockup — displays a pre-cropped PNG of the phone with bezel + app UI.
 * PNGs are generated by scripts/crop_screens.py from the source SVGs.
 */
export function PhoneMockup({
  src,
  alt = "App screen",
  blobColor = "#D6E4FF",
}: {
  src: string;
  alt?: string;
  blobColor?: string;
}) {
  return (
    <div className="relative w-full max-w-[420px] mx-auto flex items-center justify-center py-8">
      {/* Decorative blob centred behind the phone */}
      <div
        className="absolute rounded-full pointer-events-none"
        style={{
          width: "80%",
          aspectRatio: "1 / 1",
          background: `radial-gradient(closest-side, ${blobColor}, transparent 72%)`,
          zIndex: 0,
        }}
      />
      {/* Decorative accent dots */}
      <span
        className="absolute rounded-full z-[1]"
        style={{ width: 10, height: 10, background: "#DC2626", top: 20, left: 20 }}
      />
      <span
        className="absolute rounded-full z-[1]"
        style={{ width: 8, height: 8, background: "#D4AF37", top: 40, right: 10 }}
      />
      <span
        className="absolute rounded-full z-[1]"
        style={{ width: 6, height: 6, background: "#2F6CF6", bottom: 30, left: 30 }}
      />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={src}
        alt={alt}
        className="relative z-10 w-full h-auto drop-shadow-[0_30px_60px_rgba(27,58,40,0.25)]"
      />
    </div>
  );
}
